AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECS Cluster for Focason Microservices Architecture.
  This template creates an ECS Fargate cluster with CloudWatch logging,
  IAM roles for task execution and application use.

Parameters:
  ProjectName:
    Type: String
    Default: focason-cloud
    Description: Project prefix used to name all resources (must match VPC stack)

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (must match VPC stack)

  LogRetentionDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Description: Number of days to retain CloudWatch logs

Conditions:
  IsProd:
    Fn::Equals:
      - !Ref Environment
      - prod

Resources:
  # -------------------------------------------------
  # CloudWatch Log Group
  # -------------------------------------------------
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}-services"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-log-group"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # -------------------------------------------------
  # ECS Task Execution Role
  # -------------------------------------------------
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-ecs-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # AWS managed policy for ECS task execution
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        # CloudWatch Logs access
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub "${ProjectName}-ecs-custom-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow task to access ECR (pull images)
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"
              # Allow access to Parameter Store (for reading configuration)
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                Resource: "*"
              # Allow access to Secrets Manager (e.g., database passwords)
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"
              # Allow writing to CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ecs-execution-role"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------
  # ECS Task Role (for application use)
  # -------------------------------------------------
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-ecs-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub "${ProjectName}-app-access-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow application to access S3 (e.g., download config or upload files)
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource: "*"
              # Allow access to SQS queues
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource: "*"
              # Allow access to AWS MQ (RabbitMQ)
              - Effect: Allow
                Action:
                  - mq:DescribeBroker
                Resource: "*"
              # Allow access to DynamoDB or other internal resources can be extended here
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ecs-task-role"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------
  # ECS Cluster
  # -------------------------------------------------
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ProjectName}-ecs-cluster"
      CapacityProviders:
        - FARGATE
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ecs-cluster"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

# -------------------------------------------------
# Outputs
# -------------------------------------------------
Outputs:
  CloudWatchLogGroupName:
    Description: CloudWatch Log Group name for ECS services
    Value: !Ref CloudWatchLogGroup
    Export:
      Name: !Sub "${ProjectName}-log-group"

  CloudWatchLogGroupArn:
    Description: CloudWatch Log Group ARN
    Value: !GetAtt CloudWatchLogGroup.Arn
    Export:
      Name: !Sub "${ProjectName}-log-group-arn"

  ECSTaskExecutionRoleArn:
    Description: ARN of ECS Task Execution Role (used by ECS to pull images and write logs)
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub "${ProjectName}-ecs-execution-role"

  ECSTaskRoleArn:
    Description: ARN of ECS Task Role (for in-container application use)
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub "${ProjectName}-ecs-task-role"

  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${ProjectName}-ecs-cluster"

  ECSClusterArn:
    Description: ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub "${ProjectName}-ecs-cluster-arn"
