AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECS Service for Focason Gateway.
  This template creates the ECS service for Gateway with Service Discovery integration and Load Balancer.

Parameters:
  ProjectName:
    Type: String
    Default: focason-cloud
    Description: Project prefix used to name all resources (must match VPC stack)

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (must match VPC stack)

  # ECS Service Configuration
  GatewayDesiredCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    Description: Desired number of Gateway service instances

Conditions:
  IsProd:
    Fn::Equals:
      - !Ref Environment
      - prod

Resources:
  # -------------------------------------------------
  # Service Discovery Service
  # -------------------------------------------------
  FocasonGatewayDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: focason-gateway
      NamespaceId:
        Fn::ImportValue: !Sub "${ProjectName}-servicediscovery-namespace-id"
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 10
      Tags:
        - Key: Name
          Value: focason-gateway
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------
  # Focason Gateway ECS Service
  # -------------------------------------------------
  Gateway:
    Type: AWS::ECS::Service
    DependsOn: FocasonGatewayDiscovery
    Properties:
      ServiceName: !Sub "${ProjectName}-gateway"
      Cluster:
        Fn::ImportValue: !Sub "${ProjectName}-ecs-cluster"
      LaunchType: FARGATE
      DesiredCount: !Ref GatewayDesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Split
            - ","
            - Fn::ImportValue: !Sub "${ProjectName}-ecs-private-subnets"
          SecurityGroups:
            - Fn::ImportValue: !Sub "${ProjectName}-gateway-sg"
      LoadBalancers:
        - TargetGroupArn:
            Fn::ImportValue: !Sub "${ProjectName}-gateway-tg"
          ContainerName: !Sub "${ProjectName}-gateway-container"
          ContainerPort: 80
      TaskDefinition: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ProjectName}-gateway-task"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      ServiceRegistries:
        - RegistryArn: !GetAtt FocasonGatewayDiscovery.Arn
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-gateway"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

# -------------------------------------------------
# Outputs
# -------------------------------------------------
Outputs:  
  GatewayServiceDiscoveryArn:
    Description: Service Discovery ARN for Gateway
    Value: !GetAtt FocasonGatewayDiscovery.Arn
    Export:
      Name: !Sub "${ProjectName}-gateway-service-discovery-arn"

  GatewayName:
    Description: ECS Service Name for Gateway
    Value: !Ref Gateway
    Export:
      Name: !Sub "${ProjectName}-gateway"

  GatewayArn:
    Description: ECS Service ARN for Gateway
    Value: !GetAtt Gateway.ServiceArn
    Export:
      Name: !Sub "${ProjectName}-gateway-arn"
