AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECS Service for Focason Platform Service.
  This template creates the ECS service for Platform Service with Service Discovery integration and Load Balancer.

Parameters:
  ProjectName:
    Type: String
    Default: focason-cloud
    Description: Project prefix used to name all resources (must match VPC stack)

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (must match VPC stack)

  # ECS Service Configuration
  PlatformServiceDesiredCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    Description: Desired number of Platform Service instances

Conditions:
  IsProd:
    Fn::Equals:
      - !Ref Environment
      - prod

Resources:
  # -------------------------------------------------
  # Service Discovery Service
  # -------------------------------------------------
  FocasonPlatformServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: focason-platform-service
      NamespaceId:
        Fn::ImportValue: !Sub "${ProjectName}-servicediscovery-namespace-id"
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 10
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Tags:
        - Key: Name
          Value: focason-platform-service
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # -------------------------------------------------
  # Focason Platform Service ECS Service
  # -------------------------------------------------
  PlatformService:
    Type: AWS::ECS::Service
    DependsOn: FocasonPlatformServiceDiscovery
    Properties:
      ServiceName: !Sub "${ProjectName}-platform-service"
      Cluster:
        Fn::ImportValue: !Sub "${ProjectName}-ecs-cluster"
      LaunchType: FARGATE
      DesiredCount: !Ref PlatformServiceDesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Split
            - ","
            - Fn::ImportValue: !Sub "${ProjectName}-ecs-private-subnets"
          SecurityGroups:
            - Fn::ImportValue: !Sub "${ProjectName}-business-sg"
      LoadBalancers:
        - TargetGroupArn:
            Fn::ImportValue: !Sub "${ProjectName}-gateway-tg"
          ContainerName: !Sub "${ProjectName}-platform-service-container"
          ContainerPort: 8081
      TaskDefinition: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ProjectName}-platform-service-task"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      ServiceRegistries:
        - RegistryArn: !GetAtt FocasonPlatformServiceDiscovery.Arn
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-platform-service"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

# -------------------------------------------------
# Outputs
# -------------------------------------------------
Outputs:  
  PlatformServiceServiceDiscoveryArn:
    Description: Service Discovery ARN for Platform Service
    Value: !GetAtt FocasonPlatformServiceDiscovery.Arn
    Export:
      Name: !Sub "${ProjectName}-platform-service-service-discovery-arn"

  PlatformServiceServiceName:
    Description: ECS Service Name for Platform Service
    Value: !Ref PlatformService
    Export:
      Name: !Sub "${ProjectName}-platform-service"

  PlatformServiceServiceArn:
    Description: ECS Service ARN for Platform Service
    Value: !GetAtt PlatformService.ServiceArn
    Export:
      Name: !Sub "${ProjectName}-platform-service-arn"
